open_collective: intellij-rainbow-brackets
custom: https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us
custom: https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/pricing#tabs
