collective: intellij-rainbow-brackets
tiers:
  - tiers: "*"
    labels: ["backer"]
    message: "Hey <author> , thanks for supporting us on Open Collective :heart::heart::heart: We'll give a special attention to this issue!"
invitation: |
  Hey <author> :wave:,

  Thank you for opening an issue/feature request. We will get back to you as soon as we can.
  
  Please consider support us by buying a license [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M) or donating from OpenCollective <link>.
  
  And we have a [special plan](https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2586) for paid users, if you are a paid user, your issue or feature request will have a higher priority.
  
  If you are creating a issue, please make sure you already read the latest change log [here](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/CHANGELOG.md).
