name: Bug Report
description: Fire a bug report
labels: ["bug?"]
body:

  - type: dropdown
    id: new
    attributes:
      label: Have you checked the issues and discussions to ensure there are no duplicates?
      options:
        - 'No'
        - 'Yes'
    validations:
       required: true

  - type: dropdown
    id: remote
    attributes:
      label: Are you using JetBrains Client / Code With Me / IntelliJ Remote Development?
      options:
        - 'No'
        - 'JetBrains Client'
        - 'Code With Me'
        - 'IntelliJ Remote Development/Gateway'
    validations:
       required: true


  - type: input
    id: lang
    attributes:
      label: Your programming languages
      description: like Java, Python etc.
    validations:
       required: true

  - type: dropdown
    id: user
    attributes:
      label: Free or paid?
      options:
        - Free users
        - On trial
        - Paid users
        - Edu

  - type: textarea
    id: exp
    attributes:
      label: Expected Behavior
      description: what should happen
    validations:
      required: true

  - type: textarea
    id: act
    attributes:
      label: Current Behavior
      description: what happens instead of the expected behavior, any screenshots?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code snippet for reproduce
      description: Please provide a sample code snippet for reproducing bugs.
      render: shell
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Your Environment
      description: Please Copy from your IDE's *About* page
      render: shell
    validations:
      required: true
