blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions
    about: Ask questions and discuss with other community members
  - name: License issue
    url: https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2630
    about: Check your license status before you create a new issue
