blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions
    about: Ask questions and discuss with other community members
  - name: License issue
    url: https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2630
    about: Check your license status before you create a new issue
  - name: Issues about Code With Me
    url: https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2656
    about: you don't need to install Rainbow Brackets in the Code With Me client side, it works once the server side has this plugin
  - name: Issues about JetBrains Client/IntelliJ Remote Development
    url: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2584
    about: JetBrains Client/IntelliJ Remote Development not supported
  - name: Issues about Rainbow Variables/Semantic Highlighting
    url: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2760#issuecomment-2347960008
    about: Please upgrade your IDE to the latest before your raise a issue about Rainbow Variables/Semantic Highlighting
  - name: Indent guide-lines with Clion Nova
    url: https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2656
    about: Current workaround is disable the option `ReSharper C++ language engine`
